

## Create new user
# POST http://localhost:3002/users
# content-type: application/json

# {
#     "name": "testUser5",
#     "password": "testPassword",
#     "email": "testUser5@gmail.com",
#     "title": "testing manager",
#     "about": "Lorem ipsum dolem dolor"
# }

POST http://localhost:3002/users/register
content-type: application/json

{
    "name": "testUser5",
    "password": "testPassword",
    "email": "testUser5@gmail.com"
}

# GET http://localhost:3002/users/
