// Register
POST http://localhost:3001/users/register
content-type: application/json

{
    "name": "testUser6",
    "password": "testPassword",
    "email": "testUser6@gmail.com"
}

###
// Login
POST http://localhost:3001/users/login
content-type: application/json

{
    "password": "testPassword",
    "email": "testUser6@gmail.com"
}

###
// Get all users
GET http://localhost:3001/users/
